/*
 *  Copyright 2012 Steven Swor.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package cameljamod.demo.echo;

import java.util.concurrent.ExecutionException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.impl.DefaultCamelContext;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Steven Swor
 */
public class App extends javax.swing.JFrame {
    
    private final DefaultCamelContext camelContext;
    private RouteBuilder routeBuilder = null;

    /** Creates new form App */
    public App() {
        camelContext = new DefaultCamelContext();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fromLabel = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        startStopButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modbus Loopback/Echo Application");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fromLabel.setText("From");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(fromLabel, gridBagConstraints);

        fromTextField.setText("jamod:tcp://localhost:1024/discreteInputs/0?count=8&changesOnly=true");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.9;
        getContentPane().add(fromTextField, gridBagConstraints);

        toLabel.setText("To");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(toLabel, gridBagConstraints);

        toTextField.setText("jamod:tcp://localhost:1024/coils/0?count=8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.9;
        getContentPane().add(toTextField, gridBagConstraints);

        startStopButton.setText("Start");
        startStopButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                startStopButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        getContentPane().add(startStopButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startStopButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_startStopButtonItemStateChanged
        if (startStopButton.isSelected()) {
            startRoute();
        } else {
            stopRoute();
        }
    }//GEN-LAST:event_startStopButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel, except for OS X */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        if (!System.getProperty("os.name").startsWith("Mac OS X")) {
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    private void settingsEnable(final boolean enable) {
        fromLabel.setEnabled(enable);
        fromTextField.setEnabled(enable);
        toLabel.setEnabled(enable);
        toTextField.setEnabled(enable);
    }
    
    private void startRoute() {
        final String from = fromTextField.getText();
        final String to = toTextField.getText();
        routeBuilder = new RouteBuilder(camelContext) {

            @Override
            public void configure() throws Exception {
                from(from).routeId("echoRoute").log(LoggingLevel.INFO, "Received: ${body}").to(to);
            }
        };
        new SwingWorker<Object, Object>() {

            @Override
            protected Object doInBackground() throws Exception {
                camelContext.start();
                LoggerFactory.getLogger(App.class).info("Starting route");
                routeBuilder.addRoutesToCamelContext(camelContext);
                camelContext.startRoute("echoRoute");
                LoggerFactory.getLogger(App.class).info("Route started");
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    settingsEnable(false);
                    startStopButton.setText("Stop");
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } catch (ExecutionException ex) {
                    JOptionPane.showMessageDialog(App.this, ex.getCause().getLocalizedMessage(), "Error", JOptionPane.WARNING_MESSAGE);
                    settingsEnable(true);
                    startStopButton.setText("Start");
                    startStopButton.setSelected(false);
                }
            }
        }.execute();
    }
    
    private void stopRoute() {
        new SwingWorker<Object, Object>() {

            protected Object doInBackground() throws Exception {
                LoggerFactory.getLogger(App.class).info("Stopping route");
                camelContext.stopRoute("echoRoute");
                camelContext.removeRoute("echoRoute");
                LoggerFactory.getLogger(App.class).info("Route stopped");
                camelContext.stop();
                return null;
            }

            @Override
            protected void done() {
                settingsEnable(true);
                startStopButton.setText("Start");
                startStopButton.setSelected(false);
                try {
                    get();
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } catch (ExecutionException ex) {
                    JOptionPane.showMessageDialog(App.this, ex.getCause().getLocalizedMessage(), "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        }.execute();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JToggleButton startStopButton;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables

}
